name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  backend:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Ensure this is correct

    steps:
      - name: Install Dependencies
        run: npm install

  frontend:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Ensure this is correct

    steps:
      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cy:open

      
