name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

  backend:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Install Backend Dependencies
        run: npm install


  frontend:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Install Frontend Dependencies
        run: npm install

      - name: Start Frontend Server in Background
        run: npm run dev & 

      - name: Wait for Frontend to be Ready
        run: npx wait-on http://localhost:5173  

      - name: Run Cypress Tests
        run: npx cypress run  
